### ISSUE TITLE
Add support for attendees to join without the host

### ISSUE THREAD

**Issue by xMTinkerer** [xmatters/xm-labs-steps-zoom#1]
We have integrated zoom with xMatters. When we start the conference bridge, it requires host to start the meeting first, then the others will join.
We need if the host is not available, other team members will be able to start the call and discuss. Can we do that?

**Comment by xMTinkerer** [comment]
Fixed with latest commits by using the `join_before_host` setting.

**Comment by xMTinkerer** [comment]
Pending feedback.

**Comment by xMTinkerer** [comment]
Doh. Wrong button.

**Comment by sanchit231** [comment]
It is still showing waiting for host to start.

**Comment by xMTinkerer** [comment]
Hmm. In the activity stream in the flow designer canvas, do you see the `join_before_host` value being passed as "true"?

![image](https://user-images.githubusercontent.com/10202041/76988615-3481e300-6902-11ea-9c59-0feddb787fb1.png)

If it isn't there, then please review the new script edits [here](https://github.com/xmatters/xm-labs-steps-zoom/blob/master/script.js). 

If it is there, I'm wondering if there is some kind of organization wide setting? Check out this article:
https://support.zoom.us/hc/en-us/articles/202828525-Join-Before-Host

**Comment by sanchit231** [comment]
Thank you, its working fine now.

**Comment by xMTinkerer** [comment]
Awesome! What did you have to do? Was it a script update or did you need to flip a switch on the zoom side? Depending on what it was, I'll update the doc so no one else runs into that issue. 
Thanks!

**Comment by sanchit231** [comment]
I just update the join_before_host value to true. One more thing is that when we terminate the event how long the zoom link will active ?

**Comment by xMTinkerer** [comment]
Oh, sweet. 
After xMatters makes the call to zoom to create the meeting, there is no association between them. So the zoom meeting would live as long as zoom decides. The [API doc](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate) does note this:


> The start_url of a meeting is a URL using which a host or an alternative host can start a meeting. The expiration time for the start_url field is two hours for all regular users.
> For users created using the custCreate option via the  API, the expiration time of the start_url field is 90 days.
> 
> For security reasons, the recommended way to retrieve the updated value for the start_url field programmatically (after expiry) is by calling the  and referring to the value of the start_url field in the response.

But that seems to be just for the `start_url`, not the meeting itself. 
So I guess it depends on which you are interested in. Either way, the event in xMatters has no association with it.

**Comment by sanchit231** [comment]
Okay Thanks a lot for the support

**Comment by xMTinkerer** [comment]
👍
